spring:
  datasource:
    username: rsamek
    password: ${MORFEUSZ_PASSWORD}
    url: jdbc:sqlserver://morfeusz.wszib.edu.pl:1433;databaseName=rsamek;encrypt=false;
  liquibase:
    change-log: classpath:db/changelog/changelog-master.json
    enabled: true
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none